DROP TABLE DEPARTMENT CASCADE CONSTRAINTS PURGE;
DROP TABLE COURSE CASCADE CONSTRAINTS PURGE;
DROP TABLE MODULE CASCADE CONSTRAINTS PURGE;
DROP TABLE FACULTY CASCADE CONSTRAINTS PURGE;
DROP TABLE TEACHING CASCADE CONSTRAINTS PURGE;
DROP TABLE CHAIR CASCADE CONSTRAINTS PURGE;
DROP TABLE STUDENT CASCADE CONSTRAINTS PURGE;
DROP TABLE STUDENT_MODULES CASCADE CONSTRAINTS PURGE;


SET VERIFY ON
SET ECHO ON


CREATE TABLE DEPARTMENT (
	DEPT_NAME				VARCHAR (100) CONSTRAINT PKEY_DEPARTMENT PRIMARY KEY,
	PRIMARY_ADDRESS			VARCHAR (100),
	SECONDARY_ADDRESS		VARCHAR (100),
	TELNO					NUMBER (11) NOT NULL,
	FAXNO					NUMBER (11),
	EMAIL					VARCHAR (30) 
		CONSTRAINT UNIQ_DEPT_EMAIL UNIQUE NOT NULL
);

CREATE TABLE COURSE (
	COURSE_NO				CHAR (4) CONSTRAINT PKEY_COURSE PRIMARY KEY,
	COURSE_NAME				VARCHAR (100),
	COURSE_TYPE				CHAR 
		CONSTRAINT CTYPE CHECK (COURSE_TYPE IN ('U', 'P', 'R')),
	DURATION				VARCHAR (7) 
		CONSTRAINT DUR CHECK (DURATION IN ('12MTHS', '18MTHS', '1YR', '2YRS', '3YRS', '4YRS', '5YRS')),
	MODE_OF_STUDY			VARCHAR (20),
	REQ_CREDITS_TO_PASS		NUMBER (3)
		CONSTRAINT REQ_CREDITS CHECK (REQ_CREDITS_TO_PASS > 0),
	COURSE_LEADER_STAFF_NO	CHAR (7),
	DEPT_NAME				VARCHAR (100)
		CONSTRAINT FKEY_DEPARTMENT REFERENCES DEPARTMENT (DEPT_NAME)
);

CREATE TABLE MODULE (
	MODULE_NO			CHAR (6) CONSTRAINT PKEY_MODULE PRIMARY KEY,
	MODULE_NAME			VARCHAR (100),
	MODULE_LEVEL		CHAR (1) 
		CONSTRAINT MODLEV CHECK (MODULE_LEVEL IN ('1', '2', '3', '4', 'M', 'R')),
	CREDITS_HRS			NUMBER (3)
		CONSTRAINT CREDHRS CHECK (CREDITS_HRS > 0),
	COURSE_NO			CHAR (4)
		CONSTRAINT FKEY_MODULE_COURSE REFERENCES COURSE (COURSE_NO),
	MTUTOR_STAFF_NO		CHAR (7)
);

CREATE TABLE FACULTY (
	STAFF_NO			CHAR (7),	
	STAFF_NAME			VARCHAR (50) NOT NULL,
	STREET				VARCHAR (50),
	CITY				VARCHAR (20),
	REGION				VARCHAR (20),
	POSTCODE			VARCHAR (8),
	OFFICE_LOCATION		VARCHAR (100),
	ROOM_NO				NUMBER (3),
	TEL_EXT				NUMBER (3),
	EMAIL				VARCHAR (30) NOT NULL,
	HOME_TELNO			NUMBER (11),
	MOBILE_TELNO		NUMBER (11),
	KIN_NAME			VARCHAR (30),
	KIN_ADDRESS			VARCHAR (100),
	KIN_RELATIONSHIP	VARCHAR (10),
	KIN_TELNO			NUMBER (11),
	DOB					DATE NOT NULL,
	GENDER				CHAR 
		CONSTRAINT FAC_GEN CHECK (GENDER IN ('M', 'F', 'U')),
	START_DATE			DATE,
	SALARY				NUMBER (8) 
		CONSTRAINT SAL_RANGE CHECK (SALARY BETWEEN 7000 AND 150000),
	QUALIFICATIONS		VARCHAR (100) NOT NULL,
	MANAGER_STAFF_NO	CHAR (7),
	DEPT_NAME			VARCHAR (100)
		CONSTRAINT FKEY_DEPT REFERENCES DEPARTMENT (DEPT_NAME),
		CONSTRAINT PKEY_FACULTY PRIMARY KEY (STAFF_NO)
);



CREATE TABLE TEACHING (
	HOURS				NUMBER (2) 
		CONSTRAINT HRS CHECK (HOURS >= 0 AND HOURS <= 12),
	STAFF_NO			CHAR (7)
		CONSTRAINT TEACHING_FACULTY REFERENCES FACULTY (STAFF_NO),
	MODULE_NO			CHAR (6)
		CONSTRAINT TEACHING_MODULE REFERENCES MODULE (MODULE_NO),
		CONSTRAINT PKEY_TEACHING PRIMARY KEY (STAFF_NO, MODULE_NO)
);

CREATE TABLE CHAIR (
	START_DATE			DATE,
	DEPT_NAME			VARCHAR (100)
		CONSTRAINT CHAIR_DEPT REFERENCES DEPARTMENT (DEPT_NAME),
	STAFF_NO			CHAR (7)
		CONSTRAINT CHAIR_FACULTY REFERENCES FACULTY (STAFF_NO),
		CONSTRAINT PKEY_CHAIR PRIMARY KEY (DEPT_NAME, STAFF_NO)
);

CREATE TABLE STUDENT (
	STUDENT_NO				CHAR (7) CONSTRAINT PKEY_STUDENT PRIMARY KEY,
	FIRST_NAME				VARCHAR (10) NOT NULL,
	MIDDLE_NAME				VARCHAR (10),
	LAST_NAME				VARCHAR (20) NOT NULL,
	COURSE_NO				CHAR (4)
		CONSTRAINT FKEY_COURSE REFERENCES COURSE (COURSE_NO),
	START_DATE				DATE NOT NULL,
	TERM_STREET				VARCHAR (30),
	TERM_CITY				VARCHAR (20),
	TERM_REGION				VARCHAR (20),
	TERM_POSTCODE			VARCHAR (8),
	TERM_TELNO				NUMBER  (11),
	MOBILE_TELNO			NUMBER  (11),
	HOME_STREET				VARCHAR (50),
	HOME_CITY				VARCHAR (20),
	HOME_REGION				VARCHAR (20),
	HOME_POSTCODE			VARCHAR (8),
	HOME_TELNO				VARCHAR (20),
	EMAIL					VARCHAR (30) NOT NULL,
	KIN_NAME				VARCHAR (50),
	KIN_ADDRESS				VARCHAR (100),
	KIN_RELATIONSHIP		VARCHAR (20),
	KIN_TELNO				NUMBER (11),
	DOB						DATE NOT NULL,
	GENDER					CHAR (1)
		CONSTRAINT GEN CHECK (GENDER IN ('M', 'F', 'U')),
	COUNTRY_OF_ORIGIN		VARCHAR (20),
	STUTOR_STAFF_NO			CHAR (7)
		CONSTRAINT FK_FACULTY REFERENCES FACULTY (STAFF_NO)
);

CREATE TABLE STUDENT_MODULES (
	YEAR_OF_STUDY			CHAR (1) 
		CONSTRAINT STUDY_LEV CHECK (YEAR_OF_STUDY IN ('1', '2', '3', '4', 'M', 'R')),
	MARK					NUMBER (5, 2)
		CONSTRAINT STUD_MARK CHECK (MARK >= 0 AND MARK <= 100),
	RESIT_MARK				NUMBER (2)
		CONSTRAINT STUD_RESIT_MARK CHECK (RESIT_MARK >= 0 AND RESIT_MARK <= 50),
	STUDENT_NO				CHAR (7)
		CONSTRAINT STUDENT_YEAR REFERENCES STUDENT (STUDENT_NO),
	MODULE_NO				CHAR (6)
		CONSTRAINT MODULE_YEAR REFERENCES MODULE (MODULE_NO),
		CONSTRAINT PKEY_STUDENT_MODULES PRIMARY KEY (YEAR_OF_STUDY, STUDENT_NO, MODULE_NO)
);

REM Run these after data loaded

/*ALTER TABLE COURSE ADD CONSTRAINT FK_STAFF FOREIGN KEY (COURSE_LEADER_STAFF_NO) REFERENCES FACULTY (STAFF_NO);
ALTER TABLE MODULE ADD CONSTRAINT FK_MSTAFF FOREIGN KEY (MTUTOR_STAFF_NO) REFERENCES FACULTY (STAFF_NO);
ALTER TABLE FACULTY ADD CONSTRAINT FKEY_MANAGER FOREIGN KEY (MANAGER_STAFF_NO) REFERENCES FACULTY (STAFF_NO); */




	



	
	
	
	 