SET VERIFY ON
SET ECHO ON


SELECT FIRST_NAME, LAST_NAME, COURSE_NO, MODULE_NO, MARK, RESIT_MARK
FROM STUDENT NATURAL JOIN STUDENT_MODULES
WHERE STUDENT_MODULES.YEAR_OF_STUDY = 'M'
OR STUDENT_MODULES.YEAR_OF_STUDY = 'R';


SET ECHO OFF