SET VERIFY ON
SET ECHO ON

SELECT STUDENT.Last_Name AS Name, STUDENT.Home_Street AS Street, STUDENT.Home_City AS City, STUDENT.Home_Region AS Region, STUDENT.Home_Postcode AS Postcode, COURSE.DEPT_Name AS Dept
FROM STUDENT NATURAL JOIN COURSE
UNION
SELECT FACULTY.Staff_Name, FACULTY.Street, FACULTY.City, FACULTY.Region, FACULTY.Postcode, FACULTY.Dept_Name
FROM FACULTY
ORDER BY Dept;





SET ECHO OFF